### ISSUE TITLE
String Splitting 

### ISSUE THREAD

**Issue by aeakhjay** [Sruthi57/rakchamber-events#1]
EmiratesID dosn't have more than 10 parameters. the how do you access 12th  element.
```
custEID.setEmiratesId(spliter(event.getParameter("custom2").toString(), 12));
custEID.setArabicName(spliter(event.getParameter("custom2").toString(), 2));
custEID.setEnglishName(spliter(event.getParameter("custom2").toString(), 5));
custEID.setMobileNumber(spliter(event.getParameter("custom2").toString(), 9));
```

**Comment by Sruthi57** [comment]
{
lastName: "Thomas ",
gender: "Male",
fullNameAR: "جواش جوس توماس",
postalCode: "66833-2",
dateOfBirth: "1991-08-30",
fullNameEN: "Joash Jose Thomas",
arabicNationality: "الهند",
expiryDate: "2020-01-01",
firstName: "Joash Jose",
phoneNumber: "0558530094",
nationality: "IND",
issueDate: "2018-01-08",
cardNumber: "784199193293950"
}
I have taken the parameters based on this Json.
